import type { SupportedDocumentType } from '@doclens/domain';

export interface CreateUploadIntentRequest {
  /** Display metadata only. It must not be used to create a storage key. */
  originalFilename: string;
  mimeType: string;
  fileSize: number;
}

export interface CreateUploadIntentResponse {
  uploadUrl: string;
  /** Generated by the backend; it is independent from the original filename. */
  storageKey: string;
  method: 'PUT';
  expiresAt: string;
  requiredHeaders: Record<string, string>;
}

export interface CreateDocumentRequest {
  storageKey: string;
  /** Display metadata only. It must not be used to create a storage key. */
  originalFilename: string;
  mimeType: string;
  fileSize: number;
}

export type { SupportedDocumentType };
